<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MS6U17S" failures="1" tests="3" name="Test" time="58.261" errors="0" timestamp="2022-03-26T22:03:24 IST">
  <testcase classname="testcases2.Logintest" name="LoginFailiureTest" time="2.74">
    <failure type="java.lang.AssertionError" message="Invalid Credentials expected [Epic sadface: Username and password do not match any user in this service.] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: Invalid Credentials expected [Epic sadface: Username and password do not match any user in this service.] but found [Epic sadface: Username and password do not match any user in this service]
at testcases2.Logintest.LoginFailiureTest(Logintest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- LoginFailiureTest -->
  <testcase classname="testcases2.Logintest" name="LoginSuccessTest" time="0.34"/>
  <testcase classname="testcases2.Logintest" name="LoginSuccessTestExternalDataTest" time="1.137"/>
</testsuite> <!-- Test -->
